[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["data/**"]

[functions."bot"]
  external_node_modules = []

[functions."scheduled-azkar"]
  external_node_modules = []
